### ISSUE TITLE
Error when render template

### ISSUE THREAD

**Issue by fazibear** [jgaskins/opal-slim#1]
When I try to render templet get error:

```
NoMethodError: undefined method `indent_dynamic' for Temple::Utils
```

using:

```
opal (0.7.2)
opal-rails (0.7.0)
opal-slim (1.0.0)
```

**Comment by jgaskins** [comment]
What version of Slim? I may need to restrict the Slim versions `opal-slim` depends on.

Also, is this happening on the server or in the browser? Looks like it's during compilation on the server but I figured I'd check.

**Comment by fazibear** [comment]
Using `slim 3.0.6` it happened in browser. When I want to render template.

**Comment by fazibear** [comment]
Trying figure it out why it won't work and adding this helps, but think its not a solution ? 

``` ruby
  module Temple
    module Utils
      extend self
      def indent_dynamic(text, indent_next, indent, pre_tags = nil)
        text
      end
    end
  end
```

**Comment by fazibear** [comment]
Another update: if I set `Slim::Engine.options[:pretty] = true` at the top of spec file it generate wrong code. I rails `Slim::Engine.options[:pretty] = false` will work where assets are recompiled.

**Comment by jgaskins** [comment]
Hey, sorry for the delay. I've been at a conference in DC. I'll check this out now.

**Comment by jgaskins** [comment]
Odd, I'm able to render a template with `opal-slim` in an old Clearwater app (pre-virtual-DOM), even after upgrading Slim to 3.0.6. In the interest of getting a little more context and hopefully reproducing this error, can you tell me what's rendering your template?

**Comment by fazibear** [comment]
Check this PR #2. I think we don't need indented html on browser side ?
